on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
name: Gtest
jobs:
  smoke-test:
    runs-on: self-hosted
    steps:
      - name: Clean
        run: rm -rf ${GITHUB_WORKSPACE}/*
      - name: Checkout build scripts
        run: git clone ~/harness.git
      - name: Checkout zbdbench
        uses: actions/checkout@v2
        with:
          repository: westerndigitalcorporation/zbdbench
          ref: v0.1.1
          path: harness/rocksdb-context/zbdbench
      - name: Checkout rocksdb
        uses: actions/checkout@v2
        with:
          repository: metaspace/rocksdb
          ref: plugin-tests
          path: harness/rocksdb-context/rocksdb
      - name: Checkout zenfs
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: harness/rocksdb-context/rocksdb/plugin/zenfs
      - name: Build docker image
        run: cd harness && st -o logs/make-image -- make NO_VAGRANT=1 V=1 rocksdb-gtest-docker-image 
      - name: Run smoke tests
        run: cd harness && st --silent -o logs/make-gtest -- disk-select --disk 1TB -- make NO_VAGRANT=1 results/zenfs-gtest.xml 
      - name: Collect Results
        run: cd harness && make NO_VAGRANT=1 upload 
        if: always()
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: harness/results/cover-report-*.tgz
      - name: Remove images
        run: podman rmi --force --all
        if: always()
