on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * fri'
name: MTR Tests
jobs:
  mtr-tests:
    runs-on: self-hosted
    timeout-minutes: 1440
    steps:
      - name: Clean
        run: rm -rf ${GITHUB_WORKSPACE}/*
      - name: Checkout build scripts
        run: git clone ~/harness.git
      - name: Checkout percona-server
        uses: actions/checkout@v2
        with:
          repository: percona/percona-server
          ref: Percona-Server-8.0.26-16
          path: harness/percona-context/percona-server
          submodules: true
      - name: Remove default zenfs
        run: rm -r harness/percona-context/percona-server/storage/rocksdb/rocksdb_plugins/zenfs
      - name: Checkout recent zenfs
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: harness/percona-context/percona-server/storage/rocksdb/rocksdb_plugins/zenfs
      - name: Run MTR tests
        run: cd harness && make NO_VAGRANT=1 results/zenfs-mtr.xml 
      - name: Remove docker images
        run: docker image prune --force
