on:
  workflow_dispatch:
  schedule:
    - cron: '0 01 * * *'
name: Smoke RocksDB master
jobs:
  smoke-rocks-master:
    runs-on: self-hosted
    steps:
      - name: Clean
        run: rm -rf ${GITHUB_WORKSPACE}/*
      - name: Checkout build scripts
        run: git clone ~/harness.git
      - name: Checkout zbdbench
        run: git clone ~/zbdbench.git harness/rocksdb-context/zbdbench
      - name: Checkout rocksdb
        uses: actions/checkout@v2
        with:
          repository: facebook/rocksdb
          ref: main
          path: harness/rocksdb-context/rocksdb
      - name: Checkout zenfs
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: harness/rocksdb-context/rocksdb/plugin/zenfs
      - name: Run smoke tests
        run: cd harness && make NO_VAGRANT=1 results/zenfs-smoke.xml 
      - name: Collect Results
        run: cd harness && make NO_VAGRANT=1 upload 
        if: always()
      - name: Remove docker images
        run: podman rmi --force --all
        if: always()
